### ISSUE TITLE
Selection of repos based on a predefined list

### ISSUE THREAD

**Issue by albertpastrana** [intenthq/gitkv#12]
In order to prevent security issues
We should only allow the selection of the git repository based on a predefined list of allowed repos

*Acceptance criteria*
- The list is populated doing an `ls` on the `repo_root`
- If the repo passed as parameter is not the list => `404`
- If the repo is in the list, continue doing the operation with that repo
- No string interpolation is done that can lead to leaking internal paths of the server

This was raised by @nathankleyn in #11

**Comment by nathankleyn** [comment]
Upstream PR has been merged, so this can be closed. 👍
