### ISSUE TITLE
If the target directory exists, fetch/pull instead of clone

### ISSUE THREAD

**Issue by albertpastrana** [intenthq/gitkv#14]
If reusing a volume that already contains a git repo, when starting it the script will fail and it shouldn't.

We should fetch instead of clone.

**Comment by kittsville** [comment]
I think this issue is referring to [this old code](https://github.com/intenthq/gitkv/blob/a8c13b4b37b3b35dce0ddbde243ee06d452e9e00/docker/git-puller/bin/entrypoint.sh#L30), meaning it is no longer relevant.
