### ISSUE TITLE
Include the file in the URL path

### ISSUE THREAD

**Issue by kittsville** [intenthq/gitkv#25]
Wouldn't it be easier to include the file in the URL path, rather than as a parameter?

We currently use: `/repo/business-cat?file=main.go&reference=heads/master`
It could instead look like: `/repo/business-cat/main.go&reference=heads/master`

With the default ref introduced in #24 the most common use case would be very clean: `/repo/business-cat/main.go`

**Comment by nathankleyn** [comment]
I think this one we probably shouldn't do for two reasons.

If we have a file `hello/world.go` in a repo `foo`, you'll end up with a URL like this:

```rust
"/repo/foo/hello/world.go" // or,
"/repo/foo/hello/world.go?reference=sometag"
```

Which kind of trashes the REST approach to URLs of having the resource be a single segment of the path — and I believe quite a few web frameworks won't let you match on parts of URLs with unlimited slashes in it like this so could be boxing us into the frameworks that _do_ allow this.

The other reason is safety: If this file path comes from anywhere dynamic, you'll need to URL escape it. If it's in the path, it isn't easy to escape everything _except_ the slashes — whereas if it's in the query string, you can just URL escape the entire value and it'll be safe.
