### ISSUE TITLE
Package as Docker

### ISSUE THREAD

**Issue by albertpastrana** [intenthq/gitkv#5]
In order to be able to deploy the service in a docker environment
we should package it as a docker image

**Acceptance Criteria**
- Image is built as part of CI
- Image is pushed to docker hub
- Do not generate latest tag

**Comment by nathankleyn** [comment]
Fixed by #20! 👍

**Comment by nathankleyn** [comment]
Actually, going to reopen this just to request we add some documentation too for using it.

@javierpedreira / @albertpastrana You guys want to take that or should I?

**Comment by javierpedreira** [comment]
I just raised a PR to add the link. Releases should be available as soon as we generate the first version, probably after the next changes?

**Comment by nathankleyn** [comment]
Alright, think we're all done here — nice one @javierpedreira! 👏
