### ISSUE TITLE
Docker image that offers git repos as volumes

### ISSUE THREAD

**Issue by albertpastrana** [intenthq/gitkv#6]
In order to be able to use volumes with git repos in them
It'd be great if we have a docker image that provides git bare repos as volume(s)

**Acceptance Criteria**
- Can be provided with Git repo/s to clone
- We should be able to provide the list of git repo/s and (one set of) credentials assuming all repos have the same set of credentials
- Ability to configure if it should clone the bare repo or do a regular clone
- Image is published to docker hub

**Comment by nathankleyn** [comment]
https://github.com/intenthq/gitkv/pull/13 Has been done, so think thus one can be closed! @albertpastrana if this should be open still, feel free to reopen!
